---

- name: Install the latest version of bash
  apt: name=bash state=latest update_cache=yes
  become: yes

- name: Install motd
  copy: src=motd.j2 dest=/etc/update-motd.d/01-omniverse mode=0755
  changed_when: false
  become: yes

- name: Set system timezone to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
        state=link owner=root group=root force=yes
  become: yes

- name: Install globally useful system packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - libffi-dev
    - netcat
    - ntp
    - python-dev
    - strace
    - telnet
    - vim
  become: yes

- name: Enable ntpd
  service: name=ntp state=started enabled=yes
  become: yes

- name: Allow base install directory to be writable by all users
  file: path={{ base_install_dir }} mode=0777
  become: yes
