# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.hostname = "example"
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.network "private_network", ip: "192.168.150.50"
  config.vm.synced_folder "share", "/home/vagrant/Share"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
    v.memory = 8192
    v.gui = true
    v.name = "example"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.inventory_path = "../../ansible/inventory/hosts"
    ansible.playbook = "../../ansible/play_example.yml"
  end
end
